ci:
  autoupdate_commit_msg: "chore(deps): pre-commit.ci autoupdate"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: "v2.4.0"
  hooks:
  - id: setup-cfg-fmt
    args: ["--include-version-classifiers", "--max-py-version=3.11"]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["-a", "from __future__ import annotations"]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.9.0
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
  - id: nbqa-pyupgrade
    additional_dependencies: [pyupgrade==2.31.0]
    args: ["--py37-plus"]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black-jupyter

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    files: src
    additional_dependencies: ["uhi~=0.3.1", "numpy~=1.24.0", "matplotlib>3.4"]
    args: [--show-error-codes]

- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.5"
  hooks:
  - id: codespell
    args: ["-L", "hist,heros"]
    exclude: "^examples/Examples.ipynb$"

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: "v1.10.0"
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
  - id: python-no-log-warn
  - id: python-no-eval
  - id: python-use-type-annotations
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
